---
suv:
  verifiers:
    default:
      url: https://dummy.verifier.verifiablecredentials.uk
      description: Non Crypto JSON-LD Verifier
    '[#AuthenticatedVP]':
      url: http://localhost:8081
      description: Crossword's Identiproof Verifier
      didMethod: key
      signatureAlgorithm:
        - ES256
        - RS512
    '[https://www.w3.org/2018/credentials/examples/v1#CredentialManagerPresentation]':
      url: https://dummy.verifier.verifiablecredentials.uk
      description: JSON-LD Verifier (Example 24 from W3C Spec)
      didMethod: example
      signatureAlgorithm:
        - CLSignature2019

  train:
    -
      id: https://essif.trust-scheme.de/atvtrain_vc
      type: https://gitlab.grnet.gr/essif-lab/infrastructure/fraunhofer/train-source-code
      trustScheme:
        - domain_registers.vc.train.trust-scheme.de
    -
      id: https://essif.trust-scheme.de/atvtrain_vc
      type: https://train.trust-scheme.de/info/
      trustScheme:
        - domain_registers.vc.train.trust-scheme.de

  trustedIssuers:
    - "https://vc.bge.verifiablecredentials.net"
    - "https://vc.bigbank.verifiablecredentials.net"
    - "https://vc.canterbury.verifiablecredentials.net"
    - "https://vc.cleanwater.verifiablecredentials.net"
    - "https://vc.nhs.verifiablecredentials.net"
    - "https://vc.kent.verifiablecredentials.net"
    - "https://vc.poa.verifiablecredentials.net"
    - "https://vc.smallbank.verifiablecredentials.net"
    - "https://gvc.nhs.verifiablecredentials.net"
    - "https://vc.dvla.verifiablecredentials.net"

  policyMatchUrl: http://localhost:8081
  policyFormat: Identiproof
